### PR TITLE
api for google search

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by zanethomas — APPROVED** [review]

**Review by zanethomas — COMMENTED** [review]
merge conflict

**Review by zanethomas — COMMENTED** [review]
merge conflict

**Review by abbyz123 — APPROVED** [review]

**Comment by abbyz123** [comment]
My suggestion to resolve this conflict:
1. style.css: keep stylings on both sides
2. index.html. Won's update can be moved to page3.html container with id "mapShow"
3. logic.js. Won's update can be moved to a standalone javascript file (e.g. map.js) so that page3.html can independently reference it for map api.

**Comment by zanethomas** [comment]
Meng Yuan, that is a reasonable approach.

**Comment by ghost** [comment]
old request, now been updated

**Pull request closed without merging**
